app/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# @Author  : mofei
# @Time    : 2018/10/1 15:53
# @File    : view.py
# @Software: PyCharm

import base64
import json
import os
import re
import time

from flask import (
    Blueprint,
    current_app,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)
from flask_login import login_required, login_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, EqualTo, ValidationError
from werkzeug.security import generate_password_hash, check_password_hash
from app import db, login_manager
from app.models import User

bp = Blueprint('web', __name__)


login_manager.login_view = 'web.login'


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class RegisterForm(FlaskForm):
    name = StringField('name', validators=[DataRequired()])
    password = StringField('password', validators=[DataRequired()])
    confirm_password = StringField(
        'confirm_password',
        validators=[DataRequired(), EqualTo('password', '密码填入的不一致')],
    )
    submit = SubmitField('提交')

    def validate_name(self, field):
        user = User.query.filter_by(name=field.data).first()
        if user:
            raise ValidationError('该用户名已经被使用')


@bp.route('/')
@login_required
def index():
    """首页"""
    return render_template(
        'index.html',
        tab=request.args.get('tab', 'chatroom'),
    )


@bp.route('/login', methods=['GET', 'POST'])
def login():
    """登录"""
    if request.method == 'GET':
        return render_template('login.html')
    else:
        name = request.form.get('name')
        password = request.form.get('password')
        user = User.query.filter_by(name=name).first()
        if check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('web.index'))
        else:
            return render_template('login.html')


@bp.route('/register', methods=['GET', 'POST'])
def register():
    """注册"""
    form = RegisterForm()
    if request.method == 'GET':
        return render_template('register.html', form=form)
    else:
        if form.validate_on_submit():
            name = request.form.get('name')
            password = request.form.get('password')
            hashed_password = generate_password_hash(password)
            user = User(name=name, password=hashed_password, nickname=name)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('web.login'))
        else:
            return render_template('register.html', form=form)


@bp.route('/upload/', methods=['GET', 'POST'])
def upload():
    """ueditor请求后端处理，上传图片，上传涂鸦"""
    action = request.args.get('action')
    with open(
        os.path.join(current_app.static_folder, 'ueditor', 'php', 'config.json'),
        encoding='utf-8',
    ) as fp:
        try:
            CONFIG = json.loads(re.sub(r'\/\*.*\*\/', '', fp.read()))
        except:
            CONFIG = {}
    if action == 'config':
        result = CONFIG
    elif action == 'uploadimage':
        dir = 'image'
        file = request.files['upfile']
        extension = os.path.splitext(file.filename)[1]
        save_file_name = str(round(time.time() * 1000)) + extension
        save_folder = os.path.join(current_app.root_path, 'media', dir)
        url = os.path.join('/media/', dir, save_file_name)
        file.save(os.path.join(save_folder, save_file_name))
        result = {
            'state': 'SUCCESS',
            'url': url,
            'title': save_file_name,
            'original': file.filename,
        }
    elif action == 'uploadscrawl':
        dir = 'scrawl'
        data = request.form['upfile']
        data = base64.b64decode(data)
        extension = '.jpg'
        save_file_name = str(round(time.time() * 1000)) + extension
        save_path = os.path.join(current_app.root_path, 'media', dir, save_file_name)
        url = os.path.join('/media/', dir, save_file_name)
        with open(save_path, 'wb+') as f:
            f.write(data)
        result = {
            'state': 'SUCCESS',
            'url': url,
            'title': save_file_name,
            'original': save_file_name,
        }
    return json.dumps(result)


@bp.route('/media/<path:filename>')
def media_file(filename):
    """访问media下的文件"""
    return send_from_directory('media', filename)

app/templates/login.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>登录</title>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.3.1.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>

<body>
    <div class="container">
        <div class="login-box">
            <div class="login-title">
                <a>用户登录</a>
            </div>
            <form method="post">
                {# {{ form.csrf_token() }}#}
                <div class="login-input">
                    <p>
                        <a>用户名:</a>
                        <input type="text" name="name" id="username" value="">
                    </p>
                    <p>
                        <a>密 码:</a>
                        <input type="password" name="password" id="password" value="">
                    </p>
                </div>
                <div class="login-btn">
                    <input type="submit" name="login" value="登录" id="login">
                </div>
            </form>
            <a class="remind" href="{{ url_for('web.register') }}">
                <p>未有账号，前往注册</p>
            </a>
        </div>
    </div>

</body>

</html>

app/templates/register.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>注册</title>
    <script type="text/javascript" src="js/jquery-3.2.1.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <script type="text/javascript" src="../static/js/login.js"></script>
</head>

<body>
    <div class="container">
        <div class="register-box">
            <div class="register-title">
                <a>用户注册</a>
            </div>
            <form method="post">
                {{ form.csrf_token() }}
                <div class="register-input">
                    <p>
                        <a>用户名:</a>
                        <input type="text" name="name" id="username" value="">
                    </p>
                    <p>
                        <a>密 码:</a>
                        <input type="password" name="password" id="password" value="">
                    </p>
                    <p>
                        <a>重复密码:</a>
                        <input type="password" name="confirm_password" id="password" value="">
                    </p>

                </div>
                <div class="register-btn">
                    <input type="submit" name="register" value="注册" id="register">
                </div>
            </form>
            <a class="remind" href="{{ url_for('web.login') }}">
                <p>已有账号，直接登录</p>
            </a>
        </div>

    </div>

</body>

</html>